POST http://localhost:8080/articles/create
content-type: application/json

{
    "id": "1",
    "content": "New Article"
}

GET http://localhost:8080/articles/get/all
DELETE  http://localhost:8080/articles/delete/1

PUT  http://localhost:8080/articles/update/1
Content-Type: application/json

{
    "title": "Anything",
    "content": "Any content"
}